language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

  # services:
  # - mysql

  # test:
  #   adapter: mysqli
  #   database: industria
  #   username: root
  #   encoding: utf8

env:
  - CI_VERSION=3.0.0

# install vanilla CI before anything
before_install:
  - cd Industria
  - wget https://github.com/bcit-ci/CodeIgniter/archive/$CI_VERSION.tar.gz -O - | tar xz
  - cp -r application/* CodeIgniter-$CI_VERSION/application/
  - cp -r system/* CodeIgniter-$CI_VERSION/system/
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart

# install this project on top of it
install:
  - cp -r CodeIgniter-$CI_VERSION/system/* system/
  - cp -r CodeIgniter-$CI_VERSION/application/* application/
  - mv CodeIgniter-$CI_VERSION/index.php index.php
  - rm -rf CodeIgniter-$CI_VERSION

# run multiple test commands
script:
  - phpunit                  #default test command
# - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test